on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4.3.0
      with:
          pattern: my-artifacts-*
          merge-multiple: true      
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.13

    - run: pip install pipenv
    - run: pipenv install
    - run: pipenv install pyinstaller
    - run: pipenv install pillow
    - run: pipenv run pyinstaller MMC_to_vanilla_launcher.py --onefile --icon=icon.ico
    # Optionally verify that it works (provided that it does not need user interaction)
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: my-artifacts-${{ matrix.os }}
        path: dist/*
