on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4.3.0
      with:
          pattern: my-artifacts-*
          merge-multiple: true      
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.13

    - run: pip install pipenv
    - run: pipenv sync

    # 依存関係をいれる
    - name: Install dependencies
      run: |
        pipenv install flet flet-desktop flet-cli setuptools
    - run: pipenv install pillow

    # pyinstallerのインストール
    - name: install Pyinstaller
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller/bootloader
        pipenv run python ./waf distclean all
        cd ..
        pipenv run python setup.py install
        cd ~

    - run: pipenv run pip list
    - run: pipenv run pyinstaller MMC_to_vanilla_launcher.py --onefile --icon=icon.ico
    # Optionally verify that it works (provided that it does not need user interaction)
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: my-artifacts-${{ matrix.os }}
        path: dist/*
